---
title: "Fungal Analysis"
author: "Avril Metcalfe-Roach"
date: "`r Sys.Date()`"
output: html_document
---

```{r Load Elements}
library(phyloseq)
library(tidyverse)
library(ggpubr)
library(vegan)
library(Maaslin2)

# Load data
df = readxl::read_xlsx('Data Files/CARD/P-00IK_Antibiotic/ARG_master.xlsx') %>% 
  rename(MBI_ID = SampleID) %>% 
  select(MBI_ID,ARO_Accession,Drug_Class,Resistance_Mechanism,Count)

# Remove anything with zero hits
temp = df %>% group_by(ARO_Accession) %>% summarize(Count = sum(Count)) %>% ungroup %>% 
  filter(Count>0)
df = df %>% filter(ARO_Accession %in% temp$ARO_Accession)

# Abundance
o = df %>% select(MBI_ID,ARO_Accession,Count) %>% 
  pivot_wider(names_from = MBI_ID, values_from = Count) %>% 
  mutate(ARO_Accession = paste0('X_',ARO_Accession)) %>% 
  column_to_rownames('ARO_Accession') %>% as.matrix %>% 
  otu_table(taxa_are_rows = T)

# Taxonomy
t = df %>% select(Resistance_Mechanism,Drug_Class,ARO_Accession) %>% unique() %>% 
  mutate(ARO_Accession = paste0('X_',ARO_Accession)) %>% 
  `rownames<-`(.$ARO_Accession) %>% as.matrix %>% tax_table()

# Sample data
s = read.csv('Data Files/metadata.csv') %>% `rownames<-`(.$MDB_ID) %>% 
  mutate(Mouse = str_remove(Sample,'_D0') %>% str_remove('_D28'))

# Phyloseq object
ps = phyloseq(sample_data(s),o,t)
ps@sam_data$Group = factor(ps@sam_data$Group, levels = c('CON Day 0','LM Day 0','CON Day 28','LM Day 28'))

# Rarefied
set.seed(421)
ps.rar = ps %>% transform_sample_counts(function(x)round(x,0)) %>% rarefy_even_depth()
```

## Alpha Diversity

```{r}
otu = ps.rar@otu_table %>% as.matrix %>% as.data.frame
# Use Vegan package to calculate diversity
df_alpha <- diversity(t(otu), index='shannon', MARGIN = 1, base = exp(1)) %>%
  as.data.frame()
df_alpha$Sample = rownames(df_alpha)
df_alpha = df_alpha %>% left_join(s %>% select(Diet, Day) %>% rownames_to_column('Sample'))
names(df_alpha)[1] = 'shannon'
  
# Plot results - samples are paired
ggplot(df_alpha, aes(x=Diet, y=shannon)) + 
      geom_boxplot(outlier.shape = NA) +
      geom_jitter(aes(color=Day),  height = 0, width = 0.2, size=3) + 
      theme_classic(base_size = 16) +
      stat_compare_means(vjust=0.5, label.y = 2.5, paired=T, size = 5)+
      ylab('Shannon Diversity') +  xlab('') +
      facet_wrap(~Day) +
      theme(legend.position = 'none')
ggsave('Plots/Functional/P1_alphadiversity_CARD.png',height = 3.5, width = 6)
```

## Beta Diversity

```{r Calculate Beta diversity}
# Calculate the distance matrix:
beta_dist <- vegdist(t(otu), index = 'bray')
# Scaling results with NMDS
mds <- metaMDS(beta_dist)
# Extract PCoA axes and format
mds_data <- as.data.frame(mds$points)
mds_data$`Sample` <- rownames(mds_data)
mds_data <- mds_data %>% left_join(s %>% select(Diet, Day) %>% rownames_to_column('Sample')) %>% 
  mutate(beta_type = 'Bray-Curtis')

# Plot results
mds_data$Group = paste(mds_data$Diet, mds_data$Day)
mds_data$Group = factor(mds_data$Group, 
                        levels = c('CON Day 0','LM Day 0','CON Day 28','LM Day 28'))
ggplot(mds_data, aes(x = MDS1, y = MDS2, color = Group)) +
    geom_point(size = 2) + 
    stat_ellipse(size = 1) +
    theme_classic(base_size = 20) + 
    xlab('PCoA 1') + ylab('PCoA 2') +
    ggtitle('Bray-Curtis Beta Diversity')
  
ggsave('Plots/Functional/P1_betadiversity_CARD.png',height = 5, width = 7)
```

```{r Calculate Beta statistics}
# CENTROID DISTANCES (PERMANOVA)~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Format datasets
count_mat = otu %>% t() %>% as.data.frame() %>% rownames_to_column('Sample') %>% 
  left_join(mds_data %>% select(Sample, Diet, Day, Group)) %>% 
  rename(MDB_ID = Sample) %>% 
  left_join(s %>% select(Sample,MDB_ID)) %>% select(-MDB_ID) %>% 
  mutate(Group = as.character(Group))
     
# Nicely formatted otu table
otu_temp = otu %>% t %>% as.data.frame %>% rownames_to_column('Sample') %>% rename(MDB_ID = Sample) %>% 
  left_join(s %>% select(Sample,MDB_ID)) %>% select(-MDB_ID) %>% column_to_rownames('Sample')
 
# CON D0 vs D28
temp_group = count_mat$Group[str_detect(count_mat$Sample, 'CON')]
cm_con = otu_temp %>% .[str_detect(rownames(.),'CON'),]
beta_dist_con <- vegdist(cm_con, index = 'bray')
pathotype.adonis.con <- ((adonis(beta_dist_con ~ temp_group))$aov.tab)[1,6] # p value
      
# LM D0 vs D28
temp_group = count_mat$Group[str_detect(count_mat$Sample, 'LM')]
cm_lm = otu_temp %>% .[str_detect(rownames(.),'LM'),]
beta_dist_lm <- vegdist(cm_lm, index = 'bray')
pathotype.adonis.lm <- ((adonis(beta_dist_lm ~ temp_group))$aov.tab)[1,6] # p value
      
# D0 CON vs LM
temp_group = count_mat$Group[str_detect(count_mat$Sample, 'D0')]
cm_d0 = otu_temp %>% .[str_detect(rownames(.),'D0'),]
beta_dist_d0 <- vegdist(cm_d0, index = 'bray')
pathotype.adonis.d0 <- ((adonis(beta_dist_d0 ~ temp_group))$aov.tab)[1,6] # p value

# D28 CON vs LM
temp_group = count_mat$Group[str_detect(count_mat$Sample, 'D28')]
cm_d28 = otu_temp %>% .[str_detect(rownames(.),'D28'),]
beta_dist_d28 <- vegdist(cm_d28, index = 'bray')
pathotype.adonis.d28 <- ((adonis(beta_dist_d28 ~ temp_group))$aov.tab)[1,6] # p value

# CONCATENATE STATISTICS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

beta_stats = tibble(Stat = rep('Centroid Distances',4),
                    Comparison = c('CON D0 vs D28','LM D0 vs D28',
                                   'D0 CON vs LM','D28 CON vs LM'),
                    pval = c(pathotype.adonis.con, pathotype.adonis.lm,
                             pathotype.adonis.d0, pathotype.adonis.d28)) %>% 
  mutate(`p adj` = p.adjust(pval)) %>% 
  mutate(`Beta Measure` = 'Bray-Curtis') %>% 
  select(`Beta Measure`, Stat, everything()) %>% 
  mutate(pval = round(pval,4),`p adj` = round(`p adj`,4))

write.csv(beta_stats,'Results Files/Functional/S1_beta_diversity_statistics_CARD.csv',row.names = F)

rm(beta_dist,beta_dist_con,beta_dist_d0,beta_dist_d28,beta_dist_lm,
   cm_con,cm_lm,cm_d0,cm_d28,
   pathotype.adonis.con,pathotype.adonis.d0,pathotype.adonis.d28,
   pathotype.adonis.lm,
   count_mat, mds, mds_data, temp_group)
```

# Run Maaslin2
```{r}
temp = ps %>% subset_samples(Day=='Day 28')
# ARO Accession Level
maas.sp = Maaslin2(
    input_data = temp@otu_table %>% as.matrix, 
    input_metadata = s, 
    output = 'temp', 
    min_abundance = 0,
    min_prevalence = 0.3,
    max_significance = 0.05,
    normalization = 'none',
    transform = 'none',
    fixed_effects = 'Diet',
    standardize = F,
    plot_heatmap = F,
    plot_scatter = F,
    reference = 'Diet,CON')
gc()

temp = ps %>% tax_glom('Drug_Class') %>% subset_samples(Day=='Day 28')
# Drug_Class
maas.drug = Maaslin2(
    input_data = temp@otu_table %>% as.matrix, 
    input_metadata = s, 
    output = 'temp', 
    min_abundance = 0,
    min_prevalence = 0.3,
    max_significance = 0.05,
    normalization = 'none',
    transform = 'none',
    fixed_effects = 'Diet',
    standardize = F,
    plot_heatmap = F,
    plot_scatter = F,
    reference = 'Diet,CON')
gc()

temp = ps %>% tax_glom('Resistance_Mechanism') %>% subset_samples(Day=='Day 28')
# Resistance_Mechanism
maas.mech = Maaslin2(
    input_data = temp@otu_table %>% as.matrix, 
    input_metadata = s, 
    output = 'temp', 
    min_abundance = 0,
    min_prevalence = 0.3,
    max_significance = 0.05,
    normalization = 'none',
    transform = 'none',
    fixed_effects = 'Diet',
    standardize = F,
    plot_heatmap = F,
    plot_scatter = F,
    reference = 'Diet,CON')
gc()
```

```{r}
res = maas.sp$results %>% mutate(Level = "ARO_Accession") %>%
  rbind(maas.drug$results %>% mutate(Level = "Drug_Class")) %>%
  rbind(maas.mech$results %>% mutate(Level = "Resistance_Mechanism"))

sig = res %>% filter(qval<0.05)

writexl::write_xlsx(list('ARO_Accession' = res %>% filter(Level=='ARO_Accession'),
                         'Drug_Class' = res %>% filter(Level=='Drug_Class'),
                         'Resistance_Mechanism' = res %>% filter(Level=='Resistance_Mechanism')),
                    'Results Files/Functional/Maaslin2_CARD_D28.xlsx')
```