---
title: "6. Figure 4 with CARD Database"
author: "Avril Metcalfe-Roach"
date: "`r Sys.Date()`"
output: html_document
---

```{r Load Data}
library(tidyverse)
library(ggpubr)
library(VennDiagram)

# Load ARG master file from CARD database
card = readxl::read_xlsx('Data Files/CARD/P-00IK_Antibiotic/ARG_master.xlsx') %>% 
  rename(MDB_ID = SampleID) %>% 
  select(c(Protein_Accession:Resistance_Mechanism))

# Load phyloseq object & extract sample info
source('0. Initialize Bacterial Data.R')
psm = ps %>% psmelt() %>% select(-Abundance, -OTU, -c(Kingdom:Species)) %>% 
  unique %>% left_join(card) %>% 
  mutate(Resistance_Mechanism = str_to_title(Resistance_Mechanism) %>% str_wrap(30)) %>% 
  mutate(Drug_Class = str_to_title(Drug_Class) %>% str_wrap(30))

# Load qvals from Maaslin2
qval.drug = readxl::read_xlsx('Results Files/Functional/Maaslin2_CARD_D28.xlsx',sheet='Drug_Class') %>% 
  mutate(feature = str_sub(feature,start=3)) %>% rename(ARO_Accession = feature) %>% 
  left_join(psm %>% select(ARO_Accession,Drug_Class) %>% unique() %>% mutate(ARO_Accession = as.character(ARO_Accession)))
qval.mech = readxl::read_xlsx('Results Files/Functional/Maaslin2_CARD_D28.xlsx',sheet='Resistance_Mechanism') %>% 
  mutate(feature = str_sub(feature,start=3)) %>% rename(ARO_Accession = feature) %>% 
  left_join(psm %>% select(ARO_Accession,Resistance_Mechanism) %>% unique() %>% mutate(ARO_Accession = as.character(ARO_Accession)))
```

# Total CARD Counts

```{r}
psm %>% filter(Day == 'Day 28') %>% 
  group_by(Sample,Diet) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  ggplot(aes(Diet,Count, fill = Diet)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(height = 0, width = 0.2) +
  theme_classic(base_size = 16) +
  theme(legend.position = 'none') +
  stat_compare_means(comparisons = list(c('CON','LM')),size = 5) +
  xlab(NULL) + ylab('Total ARGs (RPKM)')
ggsave('Plots/Functional/P4_TotalARGs.jpeg',height=5,width=4)
```

# Resistance Mechanisms

```{r}
# 30% prevalence filter
prevfilter = psm %>% filter(Day == 'Day 28') %>% 
  group_by(Sample,Resistance_Mechanism) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Count = Count>0) %>% 
  group_by(Resistance_Mechanism) %>% 
  summarize(Count = sum(Count)/20) %>% ungroup() %>% 
  filter(Count>0.3)

# Order from most to least abundant
lm_order = psm %>% filter(Day == 'Day 28', Diet=='LM') %>% 
  group_by(Sample,Resistance_Mechanism) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  group_by(Resistance_Mechanism) %>% 
  summarize(Count = mean(Count)) %>% ungroup() %>% 
  arrange(-Count) %>% 
  filter(Resistance_Mechanism %in% prevfilter$Resistance_Mechanism)

# Filter for day 28, aggregate to mechanism level
temp = psm %>% filter(Day == 'Day 28') %>% 
  filter(Resistance_Mechanism %in% prevfilter$Resistance_Mechanism) %>% 
  group_by(Sample,Diet,Resistance_Mechanism) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Resistance_Mechanism = 
           factor(Resistance_Mechanism, levels = lm_order$Resistance_Mechanism))

# x and y value for significance labels
max_per_path = temp %>% group_by(Resistance_Mechanism) %>% summarize(M = 100+max(Count)) %>% ungroup %>% 
  mutate(Resistance_Mechanism = factor(Resistance_Mechanism, levels = lm_order$Resistance_Mechanism)) %>%
  filter(Resistance_Mechanism %in% temp$Resistance_Mechanism) %>% droplevels() %>%
  arrange(Resistance_Mechanism) %>% mutate(N = c(1:nrow(.))+0.25)

# All annotations
qvals = qval.mech %>% select(Resistance_Mechanism,qval) %>% unique %>% 
  mutate(symb = ifelse(qval>0.05,'',ifelse(qval>0.01,"  * ",
                      ifelse(qval>0.001,' **',ifelse(qval>0.0001,' ***','****'))))) %>% 
  left_join(max_per_path)

# Version 1
temp %>% 
  left_join(qvals) %>% 
  mutate(Resistance_Mechanism = factor(Resistance_Mechanism, levels = lm_order$Resistance_Mechanism)) %>% 
  ggplot(aes(Resistance_Mechanism,Count, fill = Diet)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(position = position_jitterdodge(jitter.height = 0, jitter.width = 0.2)) +
  theme_classic(base_size = 16) +
  geom_text(aes(x=N,y=M,label=symb), size = 6,lineheight=0.8,hjust=1) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  xlab(NULL) + ylab('Count (RPKM)')# +
  # scale_y_log10()
ggsave('Plots/Functional/P4_Mechanisms.jpeg',height=6,width=8)

# Version 2
lfc = psm %>% filter(Day=='Day 28') %>% 
  group_by(Sample,Diet, Resistance_Mechanism) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  group_by(Diet, Resistance_Mechanism) %>% 
  summarize(Count = mean(Count)) %>% ungroup() %>% 
  arrange(-Count) %>% 
  filter(Resistance_Mechanism %in% prevfilter$Resistance_Mechanism) %>% 
  pivot_wider(names_from = Diet, values_from = Count) %>% 
  mutate(lfc = log2(LM/CON),
         Dir = lfc>0) %>% 
  left_join(qvals)
maxlfc = max(lfc$lfc[!is.infinite(lfc$lfc)])
lfc = lfc %>% mutate(lfc_noinf = ifelse(is.infinite(lfc) & lfc<0,
                      0-(1.5*maxlfc),
                      ifelse(is.infinite(lfc) & lfc>0,
                             1.5*maxlfc,lfc)))

lfc %>% 
  arrange(-lfc) %>% 
  mutate(Resistance_Mechanism = factor(Resistance_Mechanism, levels = .$Resistance_Mechanism)) %>% 
  ggplot(aes(Resistance_Mechanism,lfc_noinf,fill=Dir)) +
  geom_col(aes(alpha = qval<0.05)) +
  scale_alpha_discrete(range = c(0.35, 1)) +
  theme_classic(base_size = 16) +
  xlab(NULL) + ylab('Log 2 Fold Change (LM/CON)') +
  theme(legend.position = 'none') +
  geom_text(aes(x=1.15,y=10,label='(Inf)'), size = 4.5,lineheight=0.8,hjust=1) +
  geom_text(aes(x=2.15,y=10,label='(Inf)'), size = 4.5,lineheight=0.8,hjust=1) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

ggsave('Plots/Functional/P4_Mechanisms_v2.jpeg',height=5,width=10)
```

# Drug Classes

```{r}
# 30% prevalence filter
prevfilter = psm %>% filter(Day == 'Day 28') %>% 
  group_by(Sample,Drug_Class) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Count = Count>0) %>% 
  group_by(Drug_Class) %>% 
  summarize(Count = sum(Count)/20) %>% ungroup() %>% 
  filter(Count>0.3)

# Order from most to least abundant
lm_order = psm %>% filter(Day == 'Day 28', Diet=='LM') %>% 
  group_by(Sample,Drug_Class) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  group_by(Drug_Class) %>% 
  summarize(Count = mean(Count)) %>% ungroup() %>% 
  arrange(-Count) %>% 
  filter(Drug_Class %in% prevfilter$Drug_Class) %>% 
  mutate(Drug_Class = Drug_Class %>% str_replace_all('\n',' ') %>% str_wrap(70))

# Filter for day 28, aggregate to mechanism level
temp = psm %>% filter(Day == 'Day 28') %>% 
  filter(Drug_Class %in% prevfilter$Drug_Class) %>% 
  group_by(Sample,Diet,Drug_Class) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Drug_Class = Drug_Class %>% str_replace_all('\n',' ') %>% str_wrap(70)) %>% 
  mutate(Drug_Class = 
           factor(Drug_Class, levels = lm_order$Drug_Class))

# x and y value for significance labels
max_per_path = temp %>% group_by(Drug_Class) %>% summarize(M = 100+max(Count)) %>% ungroup %>%
  mutate(Drug_Class = Drug_Class %>% str_replace_all('\n',' ') %>% str_wrap(70)) %>% 
  mutate(Drug_Class = factor(Drug_Class, levels = lm_order$Drug_Class)) %>%
  filter(Drug_Class %in% temp$Drug_Class) %>% droplevels() %>%
  arrange(Drug_Class) %>% mutate(N = c(1:nrow(.))+0.25)

# All annotations
qvals = qval.drug %>% select(Drug_Class,qval) %>% unique %>% 
  mutate(Drug_Class = Drug_Class %>% str_replace_all('\n',' ') %>% str_wrap(70)) %>% 
  mutate(symb = ifelse(qval>0.05,'',ifelse(qval>0.01,"  * ",
                      ifelse(qval>0.001,' **',ifelse(qval>0.0001,' ***','****'))))) %>% 
  left_join(max_per_path)

# Version 1
temp %>% filter(Drug_Class != 'N/A') %>% 
  left_join(qvals) %>% 
  mutate(Drug_Class = Drug_Class %>% str_replace_all('\n',' ') %>% str_wrap(70)) %>% 
  mutate(Drug_Class = factor(Drug_Class, levels = lm_order$Drug_Class)) %>% 
  ggplot(aes(Drug_Class,Count, fill = Diet)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(position = position_jitterdodge(jitter.height = 0, jitter.width = 0.2)) +
  theme_classic(base_size = 16) +
  geom_text(aes(x=N,y=M,label=symb), size = 6,lineheight=0.8,hjust=1) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  xlab(NULL) + ylab('Count (RPKM)')# +
  # scale_y_log10()
ggsave('Plots/Functional/CARD/P4_Drug_Classs.jpeg',height=8,width=15)
```

# Venn Diagram of ARGs

```{r}
cols = c('CON' = '#FC746E','LM' = '#01BEC3')

venn = psm %>% 
  mutate(Count = as.numeric(Count>0)) %>% 
  group_by(Group,ARO_Accession) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  filter(Count>3)# >30% prevalence 

venn.diagram(
  x = list('CON D0' = venn$ARO_Accession[venn$Group == 'CON Day 0'],
           'LM D0' = venn$ARO_Accession[venn$Group == 'LM Day 0'],
           'CON D28' = venn$ARO_Accession[venn$Group == 'CON Day 28'],
           'LM D28' = venn$ARO_Accession[venn$Group == 'LM Day 28']),
  category.names = c("CON D0","LM D0","CON D28","LM D28"),
  filename = 'Plots/Functional/P4_Venn_prev30.png',
  output = TRUE ,
  imagetype="png" ,
  height = 480 ,
  width = 480 ,
  resolution = 300,
  lwd = 1,
  col='black',
  fill = c(alpha(cols[1],1), alpha(cols[2],1),alpha(cols[1],1), alpha(cols[2],1)),
  cex = 0.7,
  fontfamily = "sans",
  cat.cex = 0.5,
  cat.default.pos = "outer",
  cat.pos = c(-27, 27, -27, 27),
  cat.dist = 0.1,
  cat.fontfamily = "sans",
  # cat.col = 'black'
)
```

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Correlate pathobionts with ARG mechanisms

```{r Prep Resistance Mechanisms}
prevfilter = psm %>% filter(Day == 'Day 28') %>% 
  group_by(Sample,Resistance_Mechanism) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Count = Count>0) %>% 
  group_by(Resistance_Mechanism) %>% 
  summarize(Count = sum(Count)/20) %>% ungroup() %>% 
  filter(Count>0.3)

lm_order = psm %>% filter(Day == 'Day 28', Diet=='LM') %>% 
  group_by(Sample,Resistance_Mechanism) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  group_by(Resistance_Mechanism) %>% 
  summarize(Count = mean(Count)) %>% ungroup() %>% 
  arrange(-Count) %>% 
  filter(Resistance_Mechanism %in% prevfilter$Resistance_Mechanism)

# Filter for day 28, aggregate to mechanism level
temp = psm %>% filter(Day == 'Day 28') %>% 
  filter(Resistance_Mechanism %in% prevfilter$Resistance_Mechanism) %>% 
  group_by(Sample,Diet,Resistance_Mechanism) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Resistance_Mechanism = 
           factor(Resistance_Mechanism, levels = lm_order$Resistance_Mechanism))

# x and y value for significance labels
max_per_path = temp %>% group_by(Resistance_Mechanism) %>% summarize(M = 100+max(Count)) %>% ungroup %>% 
  mutate(Resistance_Mechanism = factor(Resistance_Mechanism, levels = lm_order$Resistance_Mechanism)) %>%
  filter(Resistance_Mechanism %in% temp$Resistance_Mechanism) %>% droplevels() %>%
  arrange(Resistance_Mechanism) %>% mutate(N = c(1:nrow(.))+0.25)

# All annotations
qvals = qval.mech %>% select(Resistance_Mechanism,qval) %>% unique %>% 
  mutate(symb = ifelse(qval>0.05,'',ifelse(qval>0.01,"  * ",
                      ifelse(qval>0.001,' **',ifelse(qval>0.0001,' ***','****'))))) %>% 
  left_join(max_per_path)

# Resistance Mechanisms
df.res = psm %>% filter(Day == 'Day 28') %>% 
  filter(Resistance_Mechanism %in% prevfilter$Resistance_Mechanism) %>% 
  # Remove mechanisms that weren't significantly different
  filter(Resistance_Mechanism %in% qvals$Resistance_Mechanism[qvals$qval<0.05]) %>% 
  group_by(Sample,Diet,Resistance_Mechanism) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Resistance_Mechanism = 
           factor(Resistance_Mechanism, levels = lm_order$Resistance_Mechanism))
```

```{r Prep Pathobionts}
# Pathobionts of interest
# Genus level:
path.genus = c('Streptococcus','Staphylococcus','Enterococcus','Escherichia','Shigella','Haemophilus','Campylobacter','Klebsiella')
# Species level:
# NOTE: phocaeicola vulgatus = bacteroides vulgatus
path.species = c('Phocaeicola vulgatus', 'Prevotella copri','Bacteroides fragilis')
  
# Load using a function so that ps isn't overwritten
load_path = function(){
  ps = readRDS('Data Files/bacterial_phyloseq.rds')
  ps.rel = ps %>% microbiome::transform('compositional')
  
  # Maaslin stats
  maas = readxl::read_xlsx('Results Files/Bacteriome/Maaslin2_longitudinal_bacteria.xlsx',sheet='All Results')

  # Extract otu data into table
  g = ps.rel %>% subset_taxa(Genus %in% path.genus) %>% tax_glom('Genus') %>% 
    psmelt() %>% rename(Pathobiont = Genus) %>% select(-OTU) %>% select(-c(Kingdom:Family))
  sp = ps.rel %>% subset_taxa(Species %in% path.species) %>% tax_glom('Species') %>% 
    psmelt() %>% rename(Pathobiont = Species) %>% select(-OTU) %>% select(-c(Kingdom:Genus))
  
  maas2 = maas %>% filter((Level=='Genus' & Genus %in% path.genus) | (Level=='Species' & Species %in% path.species)) %>% 
    mutate(Pathobiont = ifelse(is.na(Species),Genus,Species)) %>% 
    select(Pathobiont, qval) %>% 
    mutate(symb = ifelse(qval>0.05,'',ifelse(qval>0.01,"  * ",
                        ifelse(qval>0.001,' ** ',ifelse(qval>0.0001,' ***','****')))))
  
  # sample-specific data with qvals
  path=rbind(g,sp) %>% left_join(maas2)
  return(path)
}

path = load_path()
# Remove ns pathobiont
path = path %>% filter(symb != '')

# Categorize pathobionts
path$cat = sapply(path$Pathobiont,function(x)ifelse(x %in% c('Staphylococcus','Streptococcus','Prevotella copri'),'Down','Up'))
```

```{r Run stats and plot}
df = df.res %>% left_join(path)

# CON
df.stats.con = df %>% filter(Diet=='CON',Day=='Day 28') %>% 
  group_by(Resistance_Mechanism,Pathobiont,cat) %>% 
  group_modify(~cor.test(.$Abundance,.$Count,method='spearman')[c("statistic","p.value","estimate")] %>% as.data.frame()) %>% 
  group_by(Resistance_Mechanism) %>% 
  mutate(qval = p.adjust(p.value,method='BH')) %>% ungroup %>% 
  mutate(Group = 'CON')
# LM
df.stats.lm = df %>% filter(Diet=='LM',Day=='Day 28') %>% 
  group_by(Resistance_Mechanism,Pathobiont,cat) %>% 
  group_modify(~cor.test(.$Abundance,.$Count,method='spearman')[c("statistic","p.value","estimate")] %>% as.data.frame()) %>% 
  group_by(Resistance_Mechanism) %>% 
  mutate(qval = p.adjust(p.value,method='BH')) %>% ungroup %>% 
  mutate(Group = 'LM')

df.stats = rbind(df.stats.con,df.stats.lm) %>% filter(!is.na(estimate)) %>% 
  mutate(label.lm = paste(Group,': \u03C1=',as.character(round(estimate,2)),', q=',signif(qval,2),sep='')) %>%
  mutate(label.con = ifelse(Group=='CON',label.lm,NA),
         label.lm = ifelse(Group=='LM',label.lm,NA))
  
# Arrange significance by Antibiotic Efflux ~~~~~~~~~~~~~
temp = df.stats %>% filter(Group == 'CON',Resistance_Mechanism=='Antibiotic Efflux') %>% 
  arrange(estimate)
df.stats$Pathobiont = factor(df.stats$Pathobiont, levels = temp$Pathobiont)

df.stats %>% 
  rename("Rho" = estimate) %>% 
  mutate(Qval = ifelse(qval>0.05,'',
                      ifelse(qval>0.01,'*',
                             ifelse(qval>0.001,'**',
                                    ifelse(qval<=0.001,'***',''))))) %>% 
  ggplot(aes(Resistance_Mechanism,Pathobiont,col = Rho)) +
  geom_point(size =14) +
  theme_classic(base_size = 14) +
  scale_color_gradient2(low="darkblue", high="darkred", guide="colorbar") +
  geom_text(aes(label=Qval),size = 9, col = 'white',nudge_y = -0.15) +
  ylab(NULL) + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  facet_grid(cols = vars(Group),rows = vars(cat),  scales = 'free',space = 'free')
ggsave('Plots/Functional/P4_Pathobiont_Heatmap.jpeg',height=7.5,width=6)
```

```{r Individual Plots}
df.sig = df.stats %>% filter(qval<0.05) %>% 
  mutate(comparison = paste0(Resistance_Mechanism,Pathobiont))

min_nonzero = min(df$Count[df$Count>0])

# CON hits
to_test = df.sig %>% filter(Group=='CON') %>% .$comparison
  
temp = df %>%
  mutate(comparison = paste0(Resistance_Mechanism,Pathobiont)) %>% 
  filter(comparison %in% to_test) %>% 
  mutate(Count = Count + min_nonzero/2) %>% 
  left_join(df.stats %>% select(Resistance_Mechanism,Pathobiont,Group,label.lm,label.con) %>% rename(Diet=Group))

annotations = temp %>% select(Resistance_Mechanism,Pathobiont,Diet,label.lm,label.con) %>% unique

p = temp %>% 
  ggplot(aes(Abundance,Count,col=Diet,fill=Diet)) +
  geom_point(size=1.5) +
  geom_smooth(method='lm') +
  geom_text(aes(x=0,y=1200,label=label.lm),
            data = annotations, size = 4.5,lineheight=0.8,hjust=0) +
  geom_text(aes(x=0,y=600,label=label.con),
            data = annotations, size = 4.5,lineheight=0.8,hjust=0) +
  theme_classic(base_size=14) +
  xlab('Rel. Ab, Day 28') +
  ylab('RPKM, Day 28') +
  ggh4x::facet_nested(. ~ Resistance_Mechanism + Pathobiont,
                      scales = 'free',space='free_y',axes='margins') +
  theme(legend.position = 'none') +
  scale_y_log10()
ggsave('Plots/Functional/P4_Pathobiont_CON.jpeg',height=4,width=4)

# LM hits
to_test = df.sig %>% filter(Group=='LM') %>% .$comparison
  
temp = df %>%
  mutate(comparison = paste0(Resistance_Mechanism,Pathobiont)) %>% 
  filter(comparison %in% to_test) %>% 
  mutate(Count = Count + min_nonzero/2) %>% 
  left_join(df.stats %>% select(Resistance_Mechanism,Pathobiont,Group,label.lm,label.con) %>% rename(Diet=Group))

annotations1 = temp %>% select(Resistance_Mechanism,Pathobiont,Diet,label.lm,label.con) %>% 
  unique %>% filter(Resistance_Mechanism == 'Antibiotic Efflux')
annotations2 = temp %>% select(Resistance_Mechanism,Pathobiont,Diet,label.lm,label.con) %>% 
  unique %>% filter(Resistance_Mechanism == 'Antibiotic Inactivation')

p1 = temp %>% filter(Resistance_Mechanism == 'Antibiotic Efflux') %>% 
  ggplot(aes(Abundance,Count,col=Diet,fill=Diet)) +
  geom_point(size=1.5) +
  geom_smooth(method='lm') +
  geom_text(aes(x=0,y=1200,label=label.lm),
            data = annotations1, size = 4.5,lineheight=0.8,hjust=0) +
  geom_text(aes(x=0,y=600,label=label.con),
            data = annotations1, size = 4.5,lineheight=0.8,hjust=0) +
  theme_classic(base_size=14) +
  xlab('Rel. Ab, Day 28') +
  ylab('RPKM, Day 28') +
  ggh4x::facet_nested(. ~ Resistance_Mechanism + Pathobiont,
                      scales = 'free',space='free_y',axes='margins') +
  theme(legend.position = 'none') +
  theme(axis.text.x = element_text(angle = 35, vjust = 1, hjust=1)) +
  scale_y_log10()
p2 = temp %>% filter(Resistance_Mechanism == 'Antibiotic Inactivation') %>% 
  ggplot(aes(Abundance,Count,col=Diet,fill=Diet)) +
  geom_point(size=1.5) +
  geom_smooth(method='lm') +
  geom_text(aes(x=0,y=100,label=label.lm),
            data = annotations2, size = 4.5,lineheight=0.8,hjust=0) +
  geom_text(aes(x=0,y=50,label=label.con),
            data = annotations2, size = 4.5,lineheight=0.8,hjust=0) +
  theme_classic(base_size=14) +
  xlab('Rel. Ab, Day 28') +
  ylab(NULL) +
  ggh4x::facet_nested(. ~ Resistance_Mechanism + Pathobiont,
                      scales = 'free',space='free_y',axes='margins') +
  theme(legend.position = 'none') +
  theme(axis.text.x = element_text(angle = 35, vjust = 1, hjust=1)) +
  scale_y_log10()

ggarrange(plotlist = list(p1,p2),nrow=1,widths = c(1,2))
ggsave('Plots/Functional/P4_Pathobiont_LM.jpeg',height=4,width=16)
```

```{r Save stats}
write.csv(df.stats,'Results Files/Functional/Pathobiont_vs_ARG_Mechanism_Spearman.csv',row.names = F)
```

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Correlate pathobionts with ARG drug classes

```{r Prep Drug Classes}
prevfilter = psm %>% filter(Day == 'Day 28') %>% 
  group_by(Sample,Drug_Class) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Count = Count>0) %>% 
  group_by(Drug_Class) %>% 
  summarize(Count = sum(Count)/20) %>% ungroup() %>% 
  filter(Count>0.3)

lm_order = psm %>% filter(Day == 'Day 28', Diet=='LM') %>% 
  group_by(Sample,Drug_Class) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  group_by(Drug_Class) %>% 
  summarize(Count = mean(Count)) %>% ungroup() %>% 
  arrange(-Count) %>% 
  filter(Drug_Class %in% prevfilter$Drug_Class)

# Filter for day 28, aggregate to mechanism level
temp = psm %>% filter(Day == 'Day 28') %>% 
  filter(Drug_Class %in% prevfilter$Drug_Class) %>% 
  group_by(Sample,Diet,Drug_Class) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Drug_Class = 
           factor(Drug_Class, levels = lm_order$Drug_Class))

# x and y value for significance labels
max_per_path = temp %>% group_by(Drug_Class) %>% summarize(M = 100+max(Count)) %>% ungroup %>% 
  mutate(Drug_Class = factor(Drug_Class, levels = lm_order$Drug_Class)) %>%
  filter(Drug_Class %in% temp$Drug_Class) %>% droplevels() %>%
  arrange(Drug_Class) %>% mutate(N = c(1:nrow(.))+0.25)

# All annotations
qvals = qval.drug %>% select(Drug_Class,qval) %>% unique %>% 
  mutate(symb = ifelse(qval>0.05,'',ifelse(qval>0.01,"  * ",
                      ifelse(qval>0.001,' **',ifelse(qval>0.0001,' ***','****'))))) %>% 
  left_join(max_per_path)

# Drug Classes
df.res = psm %>% filter(Day == 'Day 28') %>% 
  filter(Drug_Class %in% prevfilter$Drug_Class) %>% 
  # Remove mechanisms that weren't significantly different
  filter(Drug_Class %in% qvals$Drug_Class[qvals$qval<0.05]) %>% 
  group_by(Sample,Diet,Drug_Class) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Drug_Class = 
           factor(Drug_Class, levels = lm_order$Drug_Class))
```

```{r Prep Pathobionts}
# Pathobionts of interest
# Genus level:
path.genus = c('Streptococcus','Staphylococcus','Enterococcus','Escherichia','Shigella','Haemophilus','Campylobacter','Klebsiella')
# Species level:
# NOTE: phocaeicola vulgatus = bacteroides vulgatus
path.species = c('Phocaeicola vulgatus', 'Prevotella copri','Bacteroides fragilis')
  
# Load using a function so that ps isn't overwritten
load_path = function(){
  ps = readRDS('Data Files/bacterial_phyloseq.rds')
  ps.rel = ps %>% microbiome::transform('compositional')
  
  # Maaslin stats
  maas = readxl::read_xlsx('Results Files/Bacteriome/Maaslin2_longitudinal_bacteria.xlsx',sheet='All Results')

  # Extract otu data into table
  g = ps.rel %>% subset_taxa(Genus %in% path.genus) %>% tax_glom('Genus') %>% 
    psmelt() %>% rename(Pathobiont = Genus) %>% select(-OTU) %>% select(-c(Kingdom:Family))
  sp = ps.rel %>% subset_taxa(Species %in% path.species) %>% tax_glom('Species') %>% 
    psmelt() %>% rename(Pathobiont = Species) %>% select(-OTU) %>% select(-c(Kingdom:Genus))
  
  maas2 = maas %>% filter((Level=='Genus' & Genus %in% path.genus) | (Level=='Species' & Species %in% path.species)) %>% 
    mutate(Pathobiont = ifelse(is.na(Species),Genus,Species)) %>% 
    select(Pathobiont, qval) %>% 
    mutate(symb = ifelse(qval>0.05,'',ifelse(qval>0.01,"  * ",
                        ifelse(qval>0.001,' ** ',ifelse(qval>0.0001,' ***','****')))))
  
  # sample-specific data with qvals
  path=rbind(g,sp) %>% left_join(maas2)
  return(path)
}

path = load_path()
# Remove ns pathobiont
path = path %>% filter(symb != '')

# Categorize pathobionts
path$cat = sapply(path$Pathobiont,function(x)ifelse(x %in% c('Staphylococcus','Streptococcus','Prevotella copri'),'Down','Up'))
```

```{r Run stats and plot}
df = df.res %>% left_join(path)

# CON
df.stats.con = df %>% filter(Diet=='CON',Day=='Day 28') %>% 
  group_by(Drug_Class,Pathobiont,cat) %>% 
  group_modify(~cor.test(.$Abundance,.$Count,method='spearman')[c("statistic","p.value","estimate")] %>% as.data.frame()) %>% 
  group_by(Drug_Class) %>% 
  mutate(qval = p.adjust(p.value,method='BH')) %>% ungroup %>% 
  mutate(Group = 'CON')
# LM
df.stats.lm = df %>% filter(Diet=='LM',Day=='Day 28') %>% 
  group_by(Drug_Class,Pathobiont,cat) %>% 
  group_modify(~cor.test(.$Abundance,.$Count,method='spearman')[c("statistic","p.value","estimate")] %>% as.data.frame()) %>% 
  group_by(Drug_Class) %>% 
  mutate(qval = p.adjust(p.value,method='BH')) %>% ungroup %>% 
  mutate(Group = 'LM')

df.stats = rbind(df.stats.con,df.stats.lm) %>% filter(!is.na(estimate)) %>% 
  mutate(label.lm = paste(Group,': \u03C1=',as.character(round(estimate,2)),', q=',signif(qval,2),sep='')) %>%
  mutate(label.con = ifelse(Group=='CON',label.lm,NA),
         label.lm = ifelse(Group=='LM',label.lm,NA))
  
# Arrange significance ~~~~~~~~~~~~~
temp = df.stats %>% filter(Group == 'CON',Drug_Class=='Peptide Antibiotic') %>% 
  arrange(estimate)
df.stats$Pathobiont = factor(df.stats$Pathobiont, levels = temp$Pathobiont)

df.stats %>% 
  mutate(Drug_Class = Drug_Class %>% str_replace_all('\n',' ') %>% str_replace_all(';',', ') %>% str_wrap(50)) %>% 
  rename("Rho" = estimate) %>% 
  mutate(Qval = ifelse(qval>0.05,'',
                      ifelse(qval>0.01,'*',
                             ifelse(qval>0.001,'**',
                                    ifelse(qval<=0.001,'***',''))))) %>% 
  ggplot(aes(Drug_Class,Pathobiont,col = Rho)) +
  geom_point(size =14) +
  theme_classic(base_size = 14) +
  scale_color_gradient2(low="darkblue", high="darkred", guide="colorbar") +
  geom_text(aes(label=Qval),size = 9, col = 'white',nudge_y = -0.15) +
  ylab(NULL) + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  facet_grid(cols = vars(Group),rows = vars(cat),  scales = 'free',space = 'free')
ggsave('Plots/Functional/CARD/P4_Pathobiont_Heatmap_drug_class.jpeg',height=10,width=15)
```

```{r Individual Plots}
df.sig = df.stats %>% filter(qval<0.05) %>% 
  mutate(comparison = paste0(Drug_Class,Pathobiont))

min_nonzero = min(df$Count[df$Count>0])

# CON hits
to_test = df.sig %>% filter(Group=='CON') %>% .$comparison


# LM hits
to_test = df.sig %>% filter(Group=='LM') %>% .$comparison
  
temp = df %>%
  mutate(comparison = paste0(Drug_Class,Pathobiont)) %>% 
  filter(comparison %in% to_test) %>% 
  mutate(Count = Count + min_nonzero/2) %>% 
  left_join(df.stats %>% select(Drug_Class,Pathobiont,Group,label.lm,label.con) %>% rename(Diet=Group)) %>% 
  mutate(Drug_Class = as.character(Drug_Class))

annotations1 = temp %>% select(Drug_Class,Pathobiont,Diet,label.lm,label.con) %>% 
  unique

# For plotting

annotations1$Drug_Class[annotations1$Drug_Class=='Diaminopyrimidine\nAntibiotic;Fluoroquinolone\nAntibiotic;Glycylcycline;Nitrofuran\nAntibiotic;Tetracycline\nAntibiotic'] = 'Diaminopyrimidine Antibiotic;\nFluoroquinolone Antibiotic;\nGlycylcycline;\nNitrofuran Antibiotic;\nTetracycline Antibiotic'
temp$Drug_Class[temp$Drug_Class=='Diaminopyrimidine\nAntibiotic;Fluoroquinolone\nAntibiotic;Glycylcycline;Nitrofuran\nAntibiotic;Tetracycline\nAntibiotic'] = 'Diaminopyrimidine Antibiotic;\nFluoroquinolone Antibiotic;\nGlycylcycline;\nNitrofuran Antibiotic;\nTetracycline Antibiotic'

p1 = temp %>%
  ggplot(aes(Abundance,Count,col=Diet,fill=Diet)) +
  geom_point(size=1.5) +
  geom_smooth(method='lm') +
  geom_text(aes(x=0,y=1200,label=label.lm),
            data = annotations1, size = 4.5,lineheight=0.8,hjust=0) +
  geom_text(aes(x=0,y=600,label=label.con),
            data = annotations1, size = 4.5,lineheight=0.8,hjust=0) +
  theme_classic(base_size=14) +
  xlab('Rel. Ab, Day 28') +
  ylab('RPKM, Day 28') +
  ggh4x::facet_nested(. ~ Drug_Class + Pathobiont,
                      scales = 'free',space='free_y',axes='margins') +
  # ggh4x::facet_nested(. ~ Pathobiont + Drug_Class,
  #                     scales = 'free',space='free_y',axes='margins') +
  theme(legend.position = 'none') +
  theme(axis.text.x = element_text(angle = 35, vjust = 1, hjust=1)) +
  scale_y_log10()
ggsave('Plots/Functional/CARD/P4_Pathobiont_drug_class.jpeg',height=6,width=20)
```

```{r Save stats}
write.csv(df.stats,'Results Files/Functional/Pathobiont_vs_ARG_Drug_Classes_Spearman.csv',row.names = F)
```

