---
title: "Pathobiont Analysis"
author: "Avril Metcalfe-Roach"
date: "`r Sys.Date()`"
output: html_document
---

```{r Load}
library(phyloseq)
library(tidyverse)
library(ggpubr)
```

# BACTERIA ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
# ps output is bacterial, raw counts
ps = readRDS('Data Files/bacterial_phyloseq.rds')

ps.rel = ps %>% microbiome::transform('compositional')

# Maaslin stats
maas = readxl::read_xlsx('Results Files/Bacteriome/Fig. 1 Supplement - Bacterial Maaslin2.xlsx',sheet='All Results')

# Pathobionts of interest
# Genus level:
path.genus = c('Streptococcus','Staphylococcus','Enterococcus','Escherichia','Shigella','Haemophilus','Campylobacter','Klebsiella')
# Species level:
# NOTE: phocaeicola vulgatus = bacteroides vulgatus
path.species = c('Phocaeicola vulgatus', 'Prevotella copri','Bacteroides fragilis')

# Extract otu data into table
g = ps.rel %>% subset_taxa(Genus %in% path.genus) %>% tax_glom('Genus') %>% 
  psmelt() %>% rename(Pathobiont = Genus) %>% select(-OTU) %>% select(-c(Kingdom:Family))
sp = ps.rel %>% subset_taxa(Species %in% path.species) %>% tax_glom('Species') %>% 
  psmelt() %>% rename(Pathobiont = Species) %>% select(-OTU) %>% select(-c(Kingdom:Genus))

maas2 = maas %>% filter((Level=='Genus' & Genus %in% path.genus) | (Level=='Species' & Species %in% path.species)) %>% 
  mutate(Pathobiont = ifelse(is.na(Species),Genus,Species)) %>% 
  select(Pathobiont, qval) %>% 
  mutate(symb = ifelse(qval>0.05,'',ifelse(qval>0.01,"  * ",
                      ifelse(qval>0.001,' ** ',ifelse(qval>0.0001,' ***','****')))))

# sample-specific data with qvals
path=rbind(g,sp) %>% left_join(maas2)

# log fold change for each path
lfc = path %>% 
  group_by(Group,Pathobiont) %>% 
  summarise(Abundance = mean(Abundance)) %>% ungroup() %>% 
  pivot_wider(names_from = Group, values_from = Abundance) %>% 
  mutate(lfc = log2(`LM Day 28`/`CON Day 28`)) %>% 
  left_join(maas2) %>% 
  arrange(lfc) %>% 
  mutate(Pathobiont = factor(Pathobiont, levels = .$Pathobiont),
         Dir = ifelse(lfc>0,'Pos','Neg'),
         Sig = qval<0.05)
```

# Fig. 4a - Stacked Barplot

```{r Stacked Barplot of Pathobionts}
stack = path %>% filter(Day == 'Day 28') %>% 
  group_by(Diet,Pathobiont) %>% 
  summarise(Abundance = mean(Abundance)) %>% ungroup()
  
p1 = stack %>% 
  ggplot(aes(x = Diet, y = Abundance, fill = Pathobiont)) + 
  geom_bar(stat="identity") +
  theme_classic(base_size = 16) + 
  ylab("Rel Abundance (Day 28)") + xlab('')
ggsave('Plots/Bacteriome/Fig. 4a - Stacked Barplot.png', height = 5, width = 5)
```

# Fig. 4b - Total Pathobiont Boxplots

```{r Summed Pathobionts}
summed = path %>% filter(Day == 'Day 28') %>% 
  group_by(Sample,Diet) %>% 
  summarise(Abundance = sum(Abundance)) %>% ungroup()

p2 = summed %>%
  ggplot(aes(Diet, Abundance, fill = Diet)) +
  geom_boxplot(outlier.shape = NA) + 
  geom_jitter(height = 0, width = 0.2) +
  theme_classic(base_size = 16) + 
  ggpubr::stat_compare_means(comparisons = list(c('LM','CON')),size=5)+
  ylab('Total Pathobionts (Rel Ab, Day 28)') +
  xlab('') + theme(legend.position = 'none')
ggsave('Plots/Bacteriome/Fig. 4b - Total Pathobionts.png',height = 5, width = 5)
```

# Fig. 4c - Increased Pathobionts

```{r}
# Set order by factoring
temp_lfc = lfc %>% arrange(-`LM Day 28`) %>% 
  mutate(Pathobiont = factor(Pathobiont, levels = .$Pathobiont))
path$Pathobiont = factor(path$Pathobiont, levels = temp_lfc$Pathobiont)
maas2$Pathobiont = factor(maas2$Pathobiont, levels = temp_lfc$Pathobiont)

cols = c('CON' = '#FC746E','LM' = '#01BEC3')
max_per_path = path %>% group_by(Pathobiont) %>% summarize(M = 2*max(Abundance)) %>% ungroup %>% 
  mutate(Pathobiont = factor(Pathobiont, levels = temp_lfc$Pathobiont))
max_pos = max_per_path %>% filter(Pathobiont %in% temp_lfc$Pathobiont[temp_lfc$lfc>0]) %>% droplevels() %>%
  arrange(Pathobiont) %>% mutate(N = c(1:nrow(.))+0.25)

p3p = path %>% left_join(max_pos) %>% 
  left_join(temp_lfc) %>% left_join(maas2) %>% 
  filter(Pathobiont %in% temp_lfc$Pathobiont[temp_lfc$lfc>0]) %>% 
  mutate(Abundance = Abundance + min(.$Abundance[.$Abundance !=0])/2) %>% 
  ggplot(aes(Pathobiont, Abundance, fill = Diet)) +
   geom_boxplot(outlier.shape = NA) +
   scale_fill_manual(values = cols) +
   geom_point(position = position_jitterdodge(jitter.height = 0, jitter.width = 0.2),size=1) +
   theme_classic(base_size = 18) + 
   guides(x = guide_axis(angle = 45)) +
   ylab('Rel Abundance') + xlab('') +
  geom_text(aes(x=N,y=M,label=symb), size = 6,lineheight=0.8,hjust=1) +
  scale_y_log10()
ggsave('Plots/Bacteriome/Fig. 4c - Increased Pathobionts.png', height = 5, width =9)
```

# Fig. 4d - Decreased Pathobionts

```{r}
# Set order by factoring
temp_lfc = lfc %>% arrange(-`LM Day 28`) %>% 
  mutate(Pathobiont = factor(Pathobiont, levels = .$Pathobiont))
path$Pathobiont = factor(path$Pathobiont, levels = temp_lfc$Pathobiont)
maas2$Pathobiont = factor(maas2$Pathobiont, levels = temp_lfc$Pathobiont)

cols = c('CON' = '#FC746E','LM' = '#01BEC3')
max_per_path = path %>% group_by(Pathobiont) %>% summarize(M = 2*max(Abundance)) %>% ungroup %>% 
  mutate(Pathobiont = factor(Pathobiont, levels = temp_lfc$Pathobiont))
max_neg = max_per_path %>% filter(Pathobiont %in% temp_lfc$Pathobiont[temp_lfc$lfc<0]) %>% droplevels() %>%
arrange(Pathobiont) %>% mutate(N = c(1:nrow(.))+0.25)

p3n = path %>% left_join(max_neg) %>% 
  left_join(temp_lfc) %>% left_join(maas2) %>% 
  filter(Pathobiont %in% temp_lfc$Pathobiont[temp_lfc$lfc<0]) %>% 
  mutate(Abundance = Abundance + min(.$Abundance[.$Abundance !=0])/2) %>% 
  ggplot(aes(Pathobiont, Abundance, fill = Diet)) +
   geom_boxplot(outlier.shape = NA) +
   scale_fill_manual(values = cols) +
   geom_point(position = position_jitterdodge(jitter.height = 0, jitter.width = 0.2),size=1) +
   theme_classic(base_size = 18) + 
   guides(x = guide_axis(angle = 45)) +
   ylab('Rel Abundance') + xlab('') +
  geom_text(aes(x=N,y=M,label=symb), size = 6,lineheight=0.8,hjust=1) +
  scale_y_log10()
ggsave('Plots/Bacteriome/Fig. 4d - Decreased Pathobionts.png', height = 5, width =6)
```

# FUNGI ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Fig. 4e - Candida Genus

```{r}
# ps output is bacterial, raw counts
source('0. Initialize Fungal Data.R')

ps.rel = ps %>% microbiome::transform('compositional') %>% 
  tax_glom('Genus') %>% subset_taxa(Genus=='Candida') %>% 
  psmelt() %>% 
  mutate(Group = factor(Group, levels = c('CON Day 0','LM Day 0','CON Day 28','LM Day 28')))

comps <- list( c("CON Day 0", "LM Day 0"), 
                        c("CON Day 0", "CON Day 28"),
                        c("LM Day 0", "LM Day 28"), 
                        c("LM Day 28", "CON Day 28") )

ps.rel %>% 
  ggplot(aes(Group, Abundance, fill = Group)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(height = 0, width = 0.2) +
  theme_classic(base_size = 16) +
  ggpubr::stat_compare_means(comparisons = comps,size=5)+
  ylab('Candida (Rel Ab.)') +
  xlab(NULL) +
  theme(legend.position = 'none')
ggsave('Plots/Fungome/Fig. 4e - Candida Genus.png',height = 5, width = 6)
```

# Fig. 4f - Candida Species

```{r}
ps.rel = ps %>% subset_taxa(!is.na(Species)) %>%
  microbiome::transform('compositional') %>% 
  subset_taxa(Genus=='Candida') %>% 
  psmelt() %>% 
  mutate(Group = factor(Group, levels = c('CON Day 0','LM Day 0','CON Day 28','LM Day 28')))

comps <- list( c("CON Day 0", "LM Day 0"), 
                        c("CON Day 0", "CON Day 28"),
                        c("LM Day 0", "LM Day 28"), 
                        c("LM Day 28", "CON Day 28") )

ps.rel %>% 
  ggplot(aes(Group, Abundance, fill = Group)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(height = 0, width = 0.2) +
  theme_classic(base_size = 16) +
  ggpubr::stat_compare_means(comparisons = comps,size=5)+
  ylab('Relative Abundance') +
  xlab(NULL) +
  theme(legend.position = 'none') + facet_wrap('Species',nrow=1)
ggsave('Plots/Fungome/Fig. 4f - Candida Species.png',height = 5, width = 14)
```