---
title: "Viral Analysis"
author: "Avril Metcalfe-Roach"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(phyloseq)
library(tidyverse)
library(ggpubr)
library(vegan)
library(Maaslin2)

# ps output is bacterial, raw counts
source('0. Initialize Viral Data.R')

ps.rel = ps %>% microbiome::transform('compositional')
```

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Run Maaslin2
```{r}
s = sample_data(ps) %>% as.matrix() %>% as.data.frame

temp = ps %>% subset_samples(Day=='Day 28')
# Species
maas.sp = Maaslin2(
    input_data = temp@otu_table %>% as.matrix, 
    input_metadata = s, 
    output = 'temp', 
    min_abundance = 0,
    min_prevalence = 0.3,
    max_significance = 0.05,
    normalization = 'TSS',
    transform = 'AST',
    fixed_effects = 'Diet',
    standardize = F,
    plot_heatmap = F,
    plot_scatter = F,
    reference = 'Diet,CON')
gc()

temp = ps %>% tax_glom('Genus') %>% subset_samples(Day=='Day 28')
# Genus
maas.g = Maaslin2(
    input_data = temp@otu_table %>% as.matrix, 
    input_metadata = s, 
    output = 'temp', 
    min_abundance = 0,
    min_prevalence = 0.3,
    max_significance = 0.05,
    normalization = 'TSS',
    transform = 'AST',
    fixed_effects = 'Diet',
    standardize = F,
    plot_heatmap = F,
    plot_scatter = F,
    reference = 'Diet,CON')
gc()

temp = ps %>% tax_glom('Family') %>% subset_samples(Day=='Day 28')
# Family
maas.f = Maaslin2(
    input_data = temp@otu_table %>% as.matrix, 
    input_metadata = s, 
    output = 'temp', 
    min_abundance = 0,
    min_prevalence = 0.3,
    max_significance = 0.05,
    normalization = 'TSS',
    transform = 'AST',
    fixed_effects = 'Diet',
    standardize = F,
    plot_heatmap = F,
    plot_scatter = F,
    reference = 'Diet,CON')
gc()

temp = ps %>% tax_glom('Phylum') %>% subset_samples(Day=='Day 28')
# Phylum
maas.p = Maaslin2(
    input_data = temp@otu_table %>% as.matrix, 
    input_metadata = s, 
    output = 'temp', 
    min_abundance = 0,
    min_prevalence = 0.3,
    max_significance = 0.05,
    normalization = 'TSS',
    transform = 'AST',
    fixed_effects = 'Diet',
    standardize = F,
    plot_heatmap = F,
    plot_scatter = F,
    reference = 'Diet,CON')
gc()
```

```{r}
res = maas.sp$results %>% mutate(Level = "Species") %>%
  rbind(maas.g$results %>% mutate(Level = "Genus")) %>%
  rbind(maas.f$results %>% mutate(Level = "Family")) %>%
  rbind(maas.p$results %>% mutate(Level = "Phylum")) %>% 
  mutate(feature = str_replace_all(feature,'[^[:alnum:]|^_]','.'))

t2 = ps@tax_table %>% as.matrix %>% as.data.frame %>% rownames_to_column('OTU') %>% mutate(OTU = str_replace_all(OTU,'[^[:alnum:]|^_]','.') %>% str_replace_all('[|]','.'))

res = res %>%
  dplyr::rename(OTU = feature) %>% 
  left_join(t2) %>% 
  select(OTU,Level,everything())

res$Species[res$Level != 'Species'] = NA
res$Genus[!(res$Level %in% c('Genus','Species'))] = NA
res$Family[!(res$Level %in% c('Family','Genus','Species'))] = NA
res$Order[res$Level == 'Phylum'] = NA
res$Class[res$Level == 'Phylum'] = NA

writexl::write_xlsx(list('All Results' = res, 
                         'Phylum' = res %>% filter(Level=='Phylum'), 
                         'Family' = res %>% filter(Level=='Family'), 
                         'Genus' = res %>% filter(Level=='Genus'), 
                         'Species' = res %>% filter(Level=='Species')),
                    'Results Files/Virome/Fig. 2 Supplement - Viral Maaslin2.xlsx')
saveRDS(list(Function=maas.sp,SL3=maas.g,SL2=maas.f,SL1=maas.p),
        'Results Files/Virome/Fig. 2 Supplement - Viral Maaslin2.rds')
```