---
title: "Fungal Analysis"
author: "Avril Metcalfe-Roach"
date: "`r Sys.Date()`"
output: html_document
---

```{r Load Elements}
library(phyloseq)
library(tidyverse)
library(ggpubr)
library(vegan)
library(VennDiagram)

# Load data
df = readxl::read_xlsx('Data Files/ARG_master.xlsx') %>% 
  rename(MBI_ID = SampleID) %>% 
  select(MBI_ID,ARO_Accession,Drug_Class,Resistance_Mechanism,Count)

# Remove anything with zero hits
temp = df %>% group_by(ARO_Accession) %>% summarize(Count = sum(Count)) %>% ungroup %>% 
  filter(Count>0)
df = df %>% filter(ARO_Accession %in% temp$ARO_Accession)

# Abundance
o = df %>% select(MBI_ID,ARO_Accession,Count) %>% 
  pivot_wider(names_from = MBI_ID, values_from = Count) %>% 
  mutate(ARO_Accession = paste0('X_',ARO_Accession)) %>% 
  column_to_rownames('ARO_Accession') %>% as.matrix %>% 
  otu_table(taxa_are_rows = T)

# Taxonomy
t = df %>% select(Resistance_Mechanism,Drug_Class,ARO_Accession) %>% unique() %>% 
  mutate(ARO_Accession = paste0('X_',ARO_Accession)) %>% 
  `rownames<-`(.$ARO_Accession) %>% as.matrix %>% tax_table()

# Sample data
s = read.csv('Data Files/metadata.csv') %>% `rownames<-`(.$MDB_ID) %>% 
  mutate(Mouse = str_remove(Sample,'_D0') %>% str_remove('_D28'))

# Phyloseq object
ps = phyloseq(sample_data(s),o,t)
ps@sam_data$Group = factor(ps@sam_data$Group, levels = c('CON Day 0','LM Day 0','CON Day 28','LM Day 28'))

# Rarefied
set.seed(421)
ps.rar = ps %>% transform_sample_counts(function(x)round(x,0)) %>% rarefy_even_depth()
```

# Fig S2a - Alpha Diversity

```{r}
otu = ps.rar@otu_table %>% as.matrix %>% as.data.frame
# Use Vegan package to calculate diversity
df_alpha <- diversity(t(otu), index='shannon', MARGIN = 1, base = exp(1)) %>%
  as.data.frame()
df_alpha$Sample = rownames(df_alpha)
df_alpha = df_alpha %>% left_join(s %>% select(Diet, Day) %>% rownames_to_column('Sample'))
names(df_alpha)[1] = 'shannon'
  
# Plot results - samples are paired
p=ggplot(df_alpha, aes(x=Diet, y=shannon)) + 
      geom_boxplot(outlier.shape = NA) +
      geom_jitter(aes(color=Day),  height = 0, width = 0.2, size=3) + 
      theme_classic(base_size = 16) +
      stat_compare_means(vjust=0.5, label.y = 2.5, paired=T, size = 5)+
      ylab('Shannon Diversity') +  xlab('') +
      facet_wrap(~Day) +
      theme(legend.position = 'none')
data_s2a = p$data %>% select(Sample,Diet,Day,shannon)
ggsave('Plots/Functional/Fig S2a - CARD alpha diversity.png',height = 3.5, width = 6)
```

# Fig S2b - Beta Diversity

```{r Calculate Beta diversity}
# Calculate the distance matrix:
beta_dist <- vegdist(t(otu), index = 'bray')
# Scaling results with NMDS
mds <- metaMDS(beta_dist)
# Extract PCoA axes and format
mds_data <- as.data.frame(mds$points)
mds_data$`Sample` <- rownames(mds_data)
mds_data <- mds_data %>% left_join(s %>% select(Diet, Day) %>% rownames_to_column('Sample')) %>% 
  mutate(beta_type = 'Bray-Curtis')

# Plot results
mds_data$Group = paste(mds_data$Diet, mds_data$Day)
mds_data$Group = factor(mds_data$Group, 
                        levels = c('CON Day 0','LM Day 0','CON Day 28','LM Day 28'))
p=ggplot(mds_data, aes(x = MDS1, y = MDS2, color = Group)) +
    geom_point(size = 2) + 
    stat_ellipse(size = 1) +
    theme_classic(base_size = 20) + 
    xlab('PCoA 1') + ylab('PCoA 2') +
    ggtitle('Bray-Curtis Beta Diversity')
data_s2b = p$data
ggsave('Plots/Functional/Fig S2b - CARD beta diversity.png',height = 5, width = 7)
```

```{r Calculate Beta statistics}
# CENTROID DISTANCES (PERMANOVA)~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Format datasets
count_mat = otu %>% t() %>% as.data.frame() %>% rownames_to_column('Sample') %>% 
  left_join(mds_data %>% select(Sample, Diet, Day, Group)) %>% 
  rename(MDB_ID = Sample) %>% 
  left_join(s %>% select(Sample,MDB_ID)) %>% select(-MDB_ID) %>% 
  mutate(Group = as.character(Group))
     
# Nicely formatted otu table
otu_temp = otu %>% t %>% as.data.frame %>% rownames_to_column('Sample') %>% rename(MDB_ID = Sample) %>% 
  left_join(s %>% select(Sample,MDB_ID)) %>% select(-MDB_ID) %>% column_to_rownames('Sample')
 
# CON D0 vs D28
temp_group = count_mat$Group[str_detect(count_mat$Sample, 'CON')]
cm_con = otu_temp %>% .[str_detect(rownames(.),'CON'),]
beta_dist_con <- vegdist(cm_con, index = 'bray')
pathotype.adonis.con <- ((adonis(beta_dist_con ~ temp_group))$aov.tab)[1,6] # p value
      
# LM D0 vs D28
temp_group = count_mat$Group[str_detect(count_mat$Sample, 'LM')]
cm_lm = otu_temp %>% .[str_detect(rownames(.),'LM'),]
beta_dist_lm <- vegdist(cm_lm, index = 'bray')
pathotype.adonis.lm <- ((adonis(beta_dist_lm ~ temp_group))$aov.tab)[1,6] # p value
      
# D0 CON vs LM
temp_group = count_mat$Group[str_detect(count_mat$Sample, 'D0')]
cm_d0 = otu_temp %>% .[str_detect(rownames(.),'D0'),]
beta_dist_d0 <- vegdist(cm_d0, index = 'bray')
pathotype.adonis.d0 <- ((adonis(beta_dist_d0 ~ temp_group))$aov.tab)[1,6] # p value

# D28 CON vs LM
temp_group = count_mat$Group[str_detect(count_mat$Sample, 'D28')]
cm_d28 = otu_temp %>% .[str_detect(rownames(.),'D28'),]
beta_dist_d28 <- vegdist(cm_d28, index = 'bray')
pathotype.adonis.d28 <- ((adonis(beta_dist_d28 ~ temp_group))$aov.tab)[1,6] # p value

# CONCATENATE STATISTICS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

beta_stats = tibble(Stat = rep('Centroid Distances',4),
                    Comparison = c('CON D0 vs D28','LM D0 vs D28',
                                   'D0 CON vs LM','D28 CON vs LM'),
                    pval = c(pathotype.adonis.con, pathotype.adonis.lm,
                             pathotype.adonis.d0, pathotype.adonis.d28)) %>% 
  mutate(`p adj` = p.adjust(pval)) %>% 
  mutate(`Beta Measure` = 'Bray-Curtis') %>% 
  select(`Beta Measure`, Stat, everything()) %>% 
  mutate(pval = round(pval,4),`p adj` = round(`p adj`,4))

write.csv(beta_stats,'Results Files/Functional/Fig S2b_beta_diversity_statistics_CARD.csv',row.names = F)

rm(beta_dist,beta_dist_con,beta_dist_d0,beta_dist_d28,beta_dist_lm,
   cm_con,cm_lm,cm_d0,cm_d28,
   pathotype.adonis.con,pathotype.adonis.d0,pathotype.adonis.d28,
   pathotype.adonis.lm,
   count_mat, mds, mds_data, temp_group)
```

# Fig S2c - Venn Diagram

```{r}
card = readxl::read_xlsx('Data Files/ARG_master.xlsx') %>% 
  rename(MDB_ID = SampleID) %>% 
  select(c(Protein_Accession:Resistance_Mechanism))

# Load phyloseq object & extract sample info
ps = readRDS('Data Files/bacterial_phyloseq.rds')
psm = ps %>% psmelt() %>% select(-Abundance, -OTU, -c(Kingdom:Species)) %>% 
  unique %>% left_join(card) %>% 
  mutate(Resistance_Mechanism = str_to_title(Resistance_Mechanism) %>% str_wrap(30)) %>% 
  mutate(Drug_Class = str_to_title(Drug_Class) %>% str_wrap(30))


cols = c('CON' = '#FC746E','LM' = '#01BEC3')

venn = psm %>% 
  mutate(Count = as.numeric(Count>0)) %>% 
  group_by(Group,ARO_Accession) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  filter(Count>3)# >30% prevalence 

venn.diagram(
  x = list('CON D0' = venn$ARO_Accession[venn$Group == 'CON Day 0'],
           'LM D0' = venn$ARO_Accession[venn$Group == 'LM Day 0'],
           'CON D28' = venn$ARO_Accession[venn$Group == 'CON Day 28'],
           'LM D28' = venn$ARO_Accession[venn$Group == 'LM Day 28']),
  category.names = c("CON D0","LM D0","CON D28","LM D28"),
  filename = 'Plots/Functional/Fig S2c - VennDiagram_ARO_prevalence30.png',
  output = TRUE ,
  imagetype="png" ,
  height = 480 ,
  width = 480 ,
  resolution = 300,
  lwd = 1,
  col='black',
  fill = c(alpha(cols[1],1), alpha(cols[2],1),alpha(cols[1],1), alpha(cols[2],1)),
  cex = 0.7,
  fontfamily = "sans",
  cat.cex = 0.5,
  cat.default.pos = "outer",
  cat.pos = c(-27, 27, -27, 27),
  cat.dist = 0.1,
  cat.fontfamily = "sans",
)
# The following is 1 if there's more than 30% prevalence and 0 otherwise.
data_s2c = venn %>% 
  mutate(Count=1) %>% # Actual prevalence (/10) isn't used. Marked as 1 if more than 30% prevalence, which all of these are
  pivot_wider(names_from=Group,values_from = Count)
data_s2c[is.na(data_s2c)] = 0
```

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Fig S2d - Dot plot of ARG vs Fungi

```{r Load viruses}
# ps output is bacterial, raw counts
source('0. Initialize Fungal Data.R')
```

```{r}
# Maaslin stats
maas = readxl::read_xlsx('Results Files/Fungome/Fig. 2 Supplement - Fungal Maaslin2.xlsx',sheet='Genus') %>% filter(qval<0.01)

ps.rel = ps %>% tax_glom('Genus') %>% microbiome::transform('clr') %>% 
  subset_taxa(Genus %in% maas$Genus) %>% psmelt() %>% 
  filter(Day=='Day 28') %>% 
  left_join(maas %>% select(Genus,coef,qval)) %>% 
  mutate(symb = ifelse(qval>0.05,'',ifelse(qval>0.01,"  * ",
                      ifelse(qval>0.001,' ** ',ifelse(qval>0.0001,' ***','****')))))
```

```{r Prep CARD Data}
card = readxl::read_xlsx('Data Files/ARG_master.xlsx') %>% 
  rename(MDB_ID = SampleID) %>% 
  select(c(Protein_Accession:Resistance_Mechanism))

# Add sample info
card = card %>% left_join(sample_data(ps) %>% as.data.frame)

# 30% prevalence filter
prevfilter = card %>% filter(Day == 'Day 28') %>% 
  group_by(Sample,ARO_Accession) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Count = Count>0) %>% 
  group_by(ARO_Accession) %>% 
  summarize(Count = sum(Count)/20) %>% ungroup() %>% 
  filter(Count>0.3)
card = card %>% filter(ARO_Accession %in% prevfilter$ARO_Accession)
```

## Correlate ARGs with SEED

```{r Combine}
df = left_join(ps.rel,card) %>% mutate(Association = ifelse(coef>0,'Up','Down'))
```

```{r Run stats and plot}
# CON
df.stats.con = df %>% filter(Diet=='CON',Day=='Day 28') %>% 
  group_by(Genus,ARO_Accession,Resistance_Mechanism,Association) %>% 
  group_modify(~cor.test(.$Abundance,.$Count,method='spearman')[c("statistic","p.value","estimate")] %>% as.data.frame()) %>% 
  ungroup %>% group_by(Genus,Association) %>% 
  mutate(qval = p.adjust(p.value,method='BH')) %>% ungroup %>% 
  mutate(Group = 'CON')
# LM
df.stats.lm = df %>% filter(Diet=='LM',Day=='Day 28') %>% 
  group_by(Genus,ARO_Accession,Resistance_Mechanism,Association) %>% 
  group_modify(~cor.test(.$Abundance,.$Count,method='spearman')[c("statistic","p.value","estimate")] %>% as.data.frame()) %>% 
  ungroup %>% group_by(Genus,Association) %>% 
  mutate(qval = p.adjust(p.value,method='BH')) %>% ungroup %>% 
  mutate(Group = 'LM')

df.stats = rbind(df.stats.con,df.stats.lm) %>% filter(!is.na(estimate)) %>% 
  mutate(label.lm = paste(Group,': \u03C1=',as.character(round(estimate,2)),', q=',signif(qval,2),sep='')) %>%
  mutate(label.con = ifelse(Group=='CON',label.lm,NA),
         label.lm = ifelse(Group=='LM',label.lm,NA)) %>% 
  arrange(estimate) %>% 
  mutate(ARO_Accession = as.character(ARO_Accession))

order = df.stats %>% filter(Group=='LM',Genus==df.stats$Genus[1]) %>% 
  arrange(-estimate)
df.stats = df.stats %>% mutate(ARO_Accession = factor(ARO_Accession, levels = order$ARO_Accession))

# Arrange significance ~~~~~~~~~~~~~
p=df.stats %>% 
  mutate(Resistance_Mechanism = str_wrap(Resistance_Mechanism,25) %>% str_to_title) %>% 
  rename("Rho" = estimate) %>% 
  mutate(Qval = ifelse(qval>0.05,'',
                      ifelse(qval>0.01,'*',
                             ifelse(qval>0.001,'**',
                                    ifelse(qval<=0.001,'***',''))))) %>% 
  ggplot(aes(Genus,ARO_Accession,col = Rho)) +
  geom_point(size =14) +
  theme_classic(base_size = 14) +
  scale_color_gradient2(low="darkblue", high="darkred", guide="colorbar") +
  geom_text(aes(label=Qval),size = 9, col = 'white',nudge_y = -0.15) +
  ylab('ARG (ARO Accession)') + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  ggh4x::facet_nested(Resistance_Mechanism ~ Group + Association, scales = 'free', space = 'free') +
  # facet_grid(cols = vars(Group),rows = vars(Resistance_Mechanism), scales = 'free',space = 'free') +
  theme(strip.text.y.right = element_text(angle = 0))
data_s2d = p$data
ggsave('Plots/Functional/Fig. S2d - ARG vs Fungal Heatmap.jpeg',height=12,width=16)
```

# Save stats from S2d
```{r}
write.csv(df.stats %>% select(Genus:Resistance_Mechanism,Group,statistic:qval),
          'Results Files/Functional/Fig S2d_ARGs_vs_Fungi.csv',row.names = F)
```

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Fig S2e - Dot plot of ARGs vs viruses

```{r Load viruses}
# ps output is bacterial, raw counts
source('0. Initialize Viral Data.R')
```

```{r}
# Maaslin stats
maas = readxl::read_xlsx('Results Files/Virome/Fig. 2 Supplement - Viral Maaslin2.xlsx',sheet='Genus') %>% filter(qval<0.01)

ps.rel = ps %>% tax_glom('Genus') %>% microbiome::transform('clr') %>% 
  subset_taxa(Genus %in% maas$Genus) %>% psmelt() %>% 
  filter(Day=='Day 28') %>% 
  left_join(maas %>% select(Genus,coef,qval)) %>% 
  mutate(symb = ifelse(qval>0.05,'',ifelse(qval>0.01,"  * ",
                      ifelse(qval>0.001,' ** ',ifelse(qval>0.0001,' ***','****')))))
```

```{r Prep CARD Data}
card = readxl::read_xlsx('Data Files/ARG_master.xlsx') %>% 
  rename(MDB_ID = SampleID) %>% 
  select(c(Protein_Accession:Resistance_Mechanism))

# Add sample info
card = card %>% left_join(sample_data(ps) %>% as.data.frame)

# 30% prevalence filter
prevfilter = card %>% filter(Day == 'Day 28') %>% 
  group_by(Sample,ARO_Accession) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Count = Count>0) %>% 
  group_by(ARO_Accession) %>% 
  summarize(Count = sum(Count)/20) %>% ungroup() %>% 
  filter(Count>0.3)
card = card %>% filter(ARO_Accession %in% prevfilter$ARO_Accession)
```

## Correlate ARGs with SEED

```{r Combine}
df = left_join(ps.rel,card) %>% mutate(Association = ifelse(coef>0,'Up','Down'))
```

```{r Run stats and plot}
# CON
df.stats.con = df %>% filter(Diet=='CON',Day=='Day 28') %>% 
  group_by(Genus,ARO_Accession,Resistance_Mechanism,Association) %>% 
  group_modify(~cor.test(.$Abundance,.$Count,method='spearman')[c("statistic","p.value","estimate")] %>% as.data.frame()) %>% 
  ungroup %>% group_by(Genus,Association) %>% 
  mutate(qval = p.adjust(p.value,method='BH')) %>% ungroup %>% 
  mutate(Group = 'CON')
# LM
df.stats.lm = df %>% filter(Diet=='LM',Day=='Day 28') %>% 
  group_by(Genus,ARO_Accession,Resistance_Mechanism,Association) %>% 
  group_modify(~cor.test(.$Abundance,.$Count,method='spearman')[c("statistic","p.value","estimate")] %>% as.data.frame()) %>% 
  ungroup %>% group_by(Genus,Association) %>% 
  mutate(qval = p.adjust(p.value,method='BH')) %>% ungroup %>% 
  mutate(Group = 'LM')

df.stats = rbind(df.stats.con,df.stats.lm) %>% filter(!is.na(estimate)) %>% 
  mutate(label.lm = paste(Group,': \u03C1=',as.character(round(estimate,2)),', q=',signif(qval,2),sep='')) %>%
  mutate(label.con = ifelse(Group=='CON',label.lm,NA),
         label.lm = ifelse(Group=='LM',label.lm,NA)) %>% 
  arrange(estimate) %>% 
  mutate(ARO_Accession = as.character(ARO_Accession))

order = df.stats %>% filter(Group=='LM',Genus==df.stats$Genus[1]) %>% 
  arrange(-estimate)
df.stats = df.stats %>% mutate(ARO_Accession = factor(ARO_Accession, levels = order$ARO_Accession))

# Arrange significance ~~~~~~~~~~~~~
df.stats %>% 
  mutate(Resistance_Mechanism = str_wrap(Resistance_Mechanism,25) %>% str_to_title) %>% 
  rename("Rho" = estimate) %>% 
  mutate(Qval = ifelse(qval>0.05,'',
                      ifelse(qval>0.01,'*',
                             ifelse(qval>0.001,'**',
                                    ifelse(qval<=0.001,'***',''))))) %>% 
  ggplot(aes(Genus,ARO_Accession,col = Rho)) +
  geom_point(size =14) +
  theme_classic(base_size = 14) +
  scale_color_gradient2(low="darkblue", high="darkred", guide="colorbar") +
  geom_text(aes(label=Qval),size = 9, col = 'white',nudge_y = -0.15) +
  ylab('ARG (ARO Accession)') + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  ggh4x::facet_nested(Resistance_Mechanism ~ Group + Association, scales = 'free', space = 'free') +
  # facet_grid(cols = vars(Group),rows = vars(Resistance_Mechanism), scales = 'free',space = 'free') +
  theme(strip.text.y.right = element_text(angle = 0))
data_s2e = p$data
ggsave('Plots/Functional/Fig. S2e - ARG vs Viral Heatmap.jpeg',height=12,width=16)
```
# Save stats from S2d
```{r}
write.csv(df.stats %>% select(Genus:Resistance_Mechanism,Group,statistic:qval),
          'Results Files/Functional/Fig S2e_ARGs_vs_Viruses.csv',row.names = F)
```
#~~~~~~~~~~~~~~~~~~~~~~~




# Save Source Data

```{r}
L = list('Fig S2a' = data_s2a, 
         'Fig S2b' = data_s2b, 
         'Fig S2c' = data_s2c, 
         'Fig S2d' = data_s2d, 
         'Fig S2e' = data_s2e)
writexl::write_xlsx(L,'Source Data/Source Data Fig S2.xlsx')
```