---
title: "6. Figure 4 with CARD Database"
author: "Avril Metcalfe-Roach"
date: "`r Sys.Date()`"
output: html_document
---

```{r Load Data}
library(tidyverse)
library(ggpubr)
library(VennDiagram)

# Load ARG master file from CARD database
card = readxl::read_xlsx('Data Files/ARG_master.xlsx') %>% 
  rename(MDB_ID = SampleID) %>% 
  select(c(Protein_Accession:Resistance_Mechanism))

# Load phyloseq object & extract sample info
ps = readRDS('Data Files/bacterial_phyloseq.rds')
psm = ps %>% psmelt() %>% select(-Abundance, -OTU, -c(Kingdom:Species)) %>% 
  unique %>% left_join(card) %>% 
  mutate(Resistance_Mechanism = str_to_title(Resistance_Mechanism) %>% str_wrap(30)) %>% 
  mutate(Drug_Class = str_to_title(Drug_Class) %>% str_wrap(30))

# Load qvals from Maaslin2
getwd()
qval.drug = readxl::read_xlsx('Results Files/Functional/Fig. 5 Supplement - CARD Maaslin2.xlsx',sheet='Drug_Class') %>% 
  mutate(feature = str_sub(feature,start=3)) %>% rename(ARO_Accession = feature) %>% 
  left_join(psm %>% select(ARO_Accession,Drug_Class) %>% unique() %>% mutate(ARO_Accession = as.character(ARO_Accession)))
qval.mech = readxl::read_xlsx('Results Files/Functional/Fig. 5 Supplement - CARD Maaslin2.xlsx',sheet='Resistance_Mechanism') %>% 
  mutate(feature = str_sub(feature,start=3)) %>% rename(ARO_Accession = feature) %>% 
  left_join(psm %>% select(ARO_Accession,Resistance_Mechanism) %>% unique() %>% mutate(ARO_Accession = as.character(ARO_Accession)))
```

# Fig S3a - Drug Classes

```{r}
# 30% prevalence filter
prevfilter = psm %>% filter(Day == 'Day 28') %>% 
  group_by(Sample,Drug_Class) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Count = Count>0) %>% 
  group_by(Drug_Class) %>% 
  summarize(Count = sum(Count)/20) %>% ungroup() %>% 
  filter(Count>0.3)

# Order from most to least abundant
lm_order = psm %>% filter(Day == 'Day 28', Diet=='LM') %>% 
  group_by(Sample,Drug_Class) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  group_by(Drug_Class) %>% 
  summarize(Count = mean(Count)) %>% ungroup() %>% 
  arrange(-Count) %>% 
  filter(Drug_Class %in% prevfilter$Drug_Class) %>% 
  mutate(Drug_Class = Drug_Class %>% str_replace_all('\n',' ') %>% str_wrap(70))

# Filter for day 28, aggregate to mechanism level
temp = psm %>% filter(Day == 'Day 28') %>% 
  filter(Drug_Class %in% prevfilter$Drug_Class) %>% 
  group_by(Sample,Diet,Drug_Class) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Drug_Class = Drug_Class %>% str_replace_all('\n',' ') %>% str_wrap(70)) %>% 
  mutate(Drug_Class = 
           factor(Drug_Class, levels = lm_order$Drug_Class))

# x and y value for significance labels
max_per_path = temp %>% group_by(Drug_Class) %>% summarize(M = 100+max(Count)) %>% ungroup %>%
  mutate(Drug_Class = Drug_Class %>% str_replace_all('\n',' ') %>% str_wrap(70)) %>% 
  mutate(Drug_Class = factor(Drug_Class, levels = lm_order$Drug_Class)) %>%
  filter(Drug_Class %in% temp$Drug_Class) %>% droplevels() %>%
  arrange(Drug_Class) %>% mutate(N = c(1:nrow(.))+0.25)

# All annotations
qvals = qval.drug %>% select(Drug_Class,qval) %>% unique %>% 
  mutate(Drug_Class = Drug_Class %>% str_replace_all('\n',' ') %>% str_wrap(70)) %>% 
  mutate(symb = ifelse(qval>0.05,'',ifelse(qval>0.01,"  * ",
                      ifelse(qval>0.001,' **',ifelse(qval>0.0001,' ***','****'))))) %>% 
  left_join(max_per_path)

# Version 1
p = temp %>% filter(Drug_Class != 'N/A') %>% 
  left_join(qvals) %>% 
  mutate(Drug_Class = Drug_Class %>% str_replace_all('\n',' ') %>% str_wrap(70)) %>% 
  mutate(Drug_Class = factor(Drug_Class, levels = lm_order$Drug_Class)) %>% 
  ggplot(aes(Drug_Class,Count, fill = Diet)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(position = position_jitterdodge(jitter.height = 0, jitter.width = 0.2)) +
  theme_classic(base_size = 16) +
  geom_text(aes(x=N,y=M,label=symb), size = 6,lineheight=0.8,hjust=1) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  xlab(NULL) + ylab('Count (RPKM)')
data_s3a = p$data %>% select(-M,-N)
ggsave('Plots/Functional/Fig S3a - Dug Classes Boxplots.jpeg',height=8,width=15)
```

# Fig S3b - Correlate pathobionts with ARG drug classes

```{r Prep Drug Classes}
prevfilter = psm %>% filter(Day == 'Day 28') %>% 
  group_by(Sample,Drug_Class) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Count = Count>0) %>% 
  group_by(Drug_Class) %>% 
  summarize(Count = sum(Count)/20) %>% ungroup() %>% 
  filter(Count>0.3)

lm_order = psm %>% filter(Day == 'Day 28', Diet=='LM') %>% 
  group_by(Sample,Drug_Class) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  group_by(Drug_Class) %>% 
  summarize(Count = mean(Count)) %>% ungroup() %>% 
  arrange(-Count) %>% 
  filter(Drug_Class %in% prevfilter$Drug_Class)

# Filter for day 28, aggregate to mechanism level
temp = psm %>% filter(Day == 'Day 28') %>% 
  filter(Drug_Class %in% prevfilter$Drug_Class) %>% 
  group_by(Sample,Diet,Drug_Class) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Drug_Class = 
           factor(Drug_Class, levels = lm_order$Drug_Class))

# x and y value for significance labels
max_per_path = temp %>% group_by(Drug_Class) %>% summarize(M = 100+max(Count)) %>% ungroup %>% 
  mutate(Drug_Class = factor(Drug_Class, levels = lm_order$Drug_Class)) %>%
  filter(Drug_Class %in% temp$Drug_Class) %>% droplevels() %>%
  arrange(Drug_Class) %>% mutate(N = c(1:nrow(.))+0.25)

# All annotations
qvals = qval.drug %>% select(Drug_Class,qval) %>% unique %>% 
  mutate(symb = ifelse(qval>0.05,'',ifelse(qval>0.01,"  * ",
                      ifelse(qval>0.001,' **',ifelse(qval>0.0001,' ***','****'))))) %>% 
  left_join(max_per_path)

# Drug Classes
df.res = psm %>% filter(Day == 'Day 28') %>% 
  filter(Drug_Class %in% prevfilter$Drug_Class) %>% 
  # Remove mechanisms that weren't significantly different
  filter(Drug_Class %in% qvals$Drug_Class[qvals$qval<0.05]) %>% 
  group_by(Sample,Diet,Drug_Class) %>% 
  summarize(Count = sum(Count)) %>% ungroup() %>% 
  mutate(Drug_Class = 
           factor(Drug_Class, levels = lm_order$Drug_Class))
```

```{r Prep `Opportunistic\nBacteria`s}
# Genus level:
path.genus = c('Streptococcus','Staphylococcus','Enterococcus','Escherichia','Shigella','Haemophilus','Campylobacter','Klebsiella')
# Species level:
# NOTE: phocaeicola vulgatus = bacteroides vulgatus
path.species = c('Phocaeicola vulgatus', 'Prevotella copri','Bacteroides fragilis')
  
path = readRDS('Data Files/bacterial_phyloseq.rds')
path.rel = path %>% microbiome::transform('compositional')

# Extract otu data into table
g = path.rel %>% subset_taxa(Genus %in% path.genus) %>% tax_glom('Genus') %>% 
  psmelt() %>% rename(`Opportunistic\nBacteria` = Genus) %>% select(-OTU) %>% select(-c(Kingdom:Family))
sp = path.rel %>% subset_taxa(Species %in% path.species) %>% tax_glom('Species') %>% 
  psmelt() %>% rename(`Opportunistic\nBacteria` = Species) %>% select(-OTU) %>% select(-c(Kingdom:Genus))

# Maaslin stats
maas = readxl::read_xlsx('Results Files/Bacteriome/Fig. 1 Supplement - Bacterial Maaslin2.xlsx',sheet='All Results') %>%
  filter((Level=='Genus' & Genus %in% path.genus) | (Level=='Species' & Species %in% path.species)) %>% 
  mutate(`Opportunistic\nBacteria` = ifelse(is.na(Species),Genus,Species)) %>% 
  select(`Opportunistic\nBacteria`, qval) %>% 
  mutate(symb = ifelse(qval>0.05,'',ifelse(qval>0.01,"  * ",
                      ifelse(qval>0.001,' ** ',ifelse(qval>0.0001,' ***','****')))))

# sample-specific data with qvals
path=rbind(g,sp) %>% left_join(maas)

# Remove ns `Opportunistic\nBacteria`
path = path %>% filter(symb != '')

# Categoriz `Opportunistic\nBacteria`s
path$cat = sapply(path$`Opportunistic\nBacteria`,function(x)ifelse(x %in% c('Staphylococcus','Streptococcus','Prevotella copri'),'Down','Up'))

# Combine `Opportunistic\nBacteria` and CARD data
df = df.res %>% left_join(path %>% select(Sample, Day, Diet, Abundance, `Opportunistic\nBacteria`, cat))
```

```{r Run stats and plot}
# CON
df.stats.con = df %>% filter(Diet=='CON',Day=='Day 28') %>% 
  group_by(Drug_Class,`Opportunistic\nBacteria`,cat) %>% 
  group_modify(~cor.test(.$Abundance,.$Count,method='spearman')[c("statistic","p.value","estimate")] %>% as.data.frame()) %>% 
  group_by(Drug_Class) %>% 
  mutate(qval = p.adjust(p.value,method='BH')) %>% ungroup %>% 
  mutate(Group = 'CON')
# LM
df.stats.lm = df %>% filter(Diet=='LM',Day=='Day 28') %>% 
  group_by(Drug_Class,`Opportunistic\nBacteria`,cat) %>% 
  group_modify(~cor.test(.$Abundance,.$Count,method='spearman')[c("statistic","p.value","estimate")] %>% as.data.frame()) %>% 
  group_by(Drug_Class) %>% 
  mutate(qval = p.adjust(p.value,method='BH')) %>% ungroup %>% 
  mutate(Group = 'LM')

df.stats = rbind(df.stats.con,df.stats.lm) %>% filter(!is.na(estimate)) %>% 
  mutate(label.lm = paste(Group,': \u03C1=',as.character(round(estimate,2)),', q=',signif(qval,2),sep='')) %>%
  mutate(label.con = ifelse(Group=='CON',label.lm,NA),
         label.lm = ifelse(Group=='LM',label.lm,NA))
  
# Arrange significance ~~~~~~~~~~~~~
temp = df.stats %>% filter(Group == 'CON',Drug_Class=='Peptide Antibiotic') %>% 
  arrange(estimate)
df.stats$`Opportunistic\nBacteria` = factor(df.stats$`Opportunistic\nBacteria`, levels = temp$`Opportunistic\nBacteria`)

p=df.stats %>% 
  mutate(Drug_Class = Drug_Class %>% str_replace_all('\n',' ') %>% str_replace_all(';',', ') %>% str_wrap(50)) %>% 
  rename("Rho" = estimate) %>% 
  mutate(Qval = ifelse(qval>0.05,'',
                      ifelse(qval>0.01,'*',
                             ifelse(qval>0.001,'**',
                                    ifelse(qval<=0.001,'***',''))))) %>% 
  ggplot(aes(Drug_Class,`Opportunistic\nBacteria`,col = Rho)) +
  geom_point(size =14) +
  theme_classic(base_size = 14) +
  scale_color_gradient2(low="darkblue", high="darkred", guide="colorbar") +
  geom_text(aes(label=Qval),size = 9, col = 'white',nudge_y = -0.15) +
  ylab(NULL) + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  facet_grid(cols = vars(Group),rows = vars(cat),  scales = 'free',space = 'free')

data_s3b = p$data %>% select(Group,Drug_Class,`Opportunistic\nBacteria`,Rho,qval,label.con,label.lm)

ggsave('Plots/Functional/Fig S3b - Opportunistic Bacteria vs Drug Classes.jpeg',height=10,width=15)
```

```{r Save stats}
write.csv(df.stats,'Results Files/Functional/Opportunistic_Bacteria_vs_ARG_Drug_Classes_Spearman.csv',row.names = F)
```

```{r Save}
L = list('Fig S3a' = data_s3a,
         'Fig S3b' = data_s3b)
writexl::write_xlsx(L,'Source Data/Source Data Fig S3.xlsx')
```